swagger: "2.0"
info:
  title: Enduro API
  version: ""
host: localhost:9000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /batch:
    get:
      tags:
      - batch
      summary: status batch
      description: Retrieve status of current batch operation.
      operationId: batch#status
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BatchStatusResponseBody'
            required:
            - running
      schemes:
      - http
    post:
      tags:
      - batch
      summary: submit batch
      description: Submit a new batch
      operationId: batch#submit
      parameters:
      - name: SubmitRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BatchSubmitRequestBody'
          required:
          - path
      responses:
        "202":
          description: Accepted response.
          schema:
            $ref: '#/definitions/BatchSubmitResponseBody'
            required:
            - workflow_id
            - run_id
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/BatchSubmitNotValidResponseBody'
        "409":
          description: Conflict response.
          schema:
            $ref: '#/definitions/BatchSubmitNotAvailableResponseBody'
      schemes:
      - http
  /batch/hints:
    get:
      tags:
      - batch
      summary: hints batch
      description: Retrieve form hints
      operationId: batch#hints
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BatchHintsResponseBody'
      schemes:
      - http
  /collection:
    get:
      tags:
      - collection
      summary: list collection
      description: List all stored collections
      operationId: collection#list
      parameters:
      - name: name
        in: query
        required: false
        type: string
      - name: original_id
        in: query
        required: false
        type: string
      - name: transfer_id
        in: query
        required: false
        type: string
        format: uuid
      - name: aip_id
        in: query
        required: false
        type: string
        format: uuid
      - name: pipeline_id
        in: query
        required: false
        type: string
        format: uuid
      - name: earliest_created_time
        in: query
        required: false
        type: string
        format: date-time
      - name: latest_created_time
        in: query
        required: false
        type: string
        format: date-time
      - name: status
        in: query
        required: false
        type: string
        enum:
        - new
        - in progress
        - done
        - error
        - unknown
        - queued
        - pending
        - abandoned
      - name: cursor
        in: query
        description: Pagination cursor
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionListResponseBody'
            required:
            - items
      schemes:
      - http
  /collection/{id}:
    get:
      tags:
      - collection
      summary: show collection
      description: Show collection by ID
      operationId: collection#show
      parameters:
      - name: id
        in: path
        description: Identifier of collection to show
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionShowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionShowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
    delete:
      tags:
      - collection
      summary: delete collection
      description: Delete collection by ID
      operationId: collection#delete
      parameters:
      - name: id
        in: path
        description: Identifier of collection to delete
        required: true
        type: integer
      responses:
        "204":
          description: No Content response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionDeleteNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/cancel:
    post:
      tags:
      - collection
      summary: cancel collection
      description: Cancel collection processing by ID
      operationId: collection#cancel
      parameters:
      - name: id
        in: path
        description: Identifier of collection to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CollectionCancelNotRunningResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionCancelNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/decision:
    post:
      tags:
      - collection
      summary: decide collection
      description: Make decision for a pending collection by ID
      operationId: collection#decide
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        type: integer
      - name: object
        in: body
        required: true
        schema:
          type: object
          properties:
            option:
              type: string
              description: Decision option to proceed with
              example: Iure sunt fugiat voluptate.
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CollectionDecideNotValidResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionDecideNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/download:
    get:
      tags:
      - collection
      summary: download collection
      description: Download collection by ID
      operationId: collection#download
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: string
            format: byte
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionDownloadNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/retry:
    post:
      tags:
      - collection
      summary: retry collection
      description: Retry collection processing by ID
      operationId: collection#retry
      parameters:
      - name: id
        in: path
        description: Identifier of collection to retry
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CollectionRetryNotRunningResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionRetryNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/{id}/workflow:
    get:
      tags:
      - collection
      summary: workflow collection
      description: Retrieve workflow status by ID
      operationId: collection#workflow
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionWorkflowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CollectionWorkflowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /collection/bulk:
    get:
      tags:
      - collection
      summary: bulk_status collection
      description: Retrieve status of current bulk operation.
      operationId: collection#bulk_status
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CollectionBulkStatusResponseBody'
            required:
            - running
      schemes:
      - http
    post:
      tags:
      - collection
      summary: bulk collection
      description: Bulk operations (retry, cancel...).
      operationId: collection#bulk
      parameters:
      - name: BulkRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CollectionBulkRequestBody'
          required:
          - operation
          - status
      responses:
        "202":
          description: Accepted response.
          schema:
            $ref: '#/definitions/CollectionBulkResponseBody'
            required:
            - workflow_id
            - run_id
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CollectionBulkNotValidResponseBody'
        "409":
          description: Conflict response.
          schema:
            $ref: '#/definitions/CollectionBulkNotAvailableResponseBody'
      schemes:
      - http
  /collection/monitor:
    get:
      tags:
      - collection
      summary: monitor collection
      operationId: collection#monitor
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/CollectionMonitorResponseBody'
      schemes:
      - ws
  /eark:
    get:
      tags:
      - eark
      summary: status eark
      description: Retrieve status of current eark operation.
      operationId: eark#status
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/EarkStatusResponseBody'
            required:
            - running
      schemes:
      - http
    post:
      tags:
      - eark
      summary: submit eark
      description: Submit a new eark
      operationId: eark#submit
      responses:
        "202":
          description: Accepted response.
          schema:
            $ref: '#/definitions/EarkSubmitResponseBody'
            required:
            - workflow_id
            - run_id
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/EarkSubmitNotValidResponseBody'
        "409":
          description: Conflict response.
          schema:
            $ref: '#/definitions/EarkSubmitNotAvailableResponseBody'
      schemes:
      - http
  /pipeline:
    get:
      tags:
      - pipeline
      summary: list pipeline
      description: List all known pipelines
      operationId: pipeline#list
      parameters:
      - name: name
        in: query
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/EnduroStoredPipelineResponse'
      schemes:
      - http
  /pipeline/{id}:
    get:
      tags:
      - pipeline
      summary: show pipeline
      description: Show pipeline by ID
      operationId: pipeline#show
      parameters:
      - name: id
        in: path
        description: Identifier of pipeline to show
        required: true
        type: string
        format: uuid
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PipelineShowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/PipelineShowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /pipeline/{id}/processing:
    get:
      tags:
      - pipeline
      summary: processing pipeline
      description: List all processing configurations of a pipeline given its ID
      operationId: pipeline#processing
      parameters:
      - name: id
        in: path
        description: Identifier of pipeline
        required: true
        type: string
        format: uuid
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Voluptates et molestiae eum et occaecati.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/PipelineProcessingNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download internal/api/gen/http/openapi.json
      description: JSON document containing the API swagger definition.
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  BatchHintsResponseBody:
    title: BatchHintsResponseBody
    type: object
    properties:
      completed_dirs:
        type: array
        items:
          type: string
          example: Ab est sed reiciendis ipsum.
        description: A list of known values of completedDir used by existing watchers.
        example:
        - Saepe quibusdam aut magnam itaque.
        - Dolor quo.
        - Vitae suscipit.
        - Ullam cumque recusandae quae porro corporis.
    example:
      completed_dirs:
      - Rerum voluptatem non quas.
      - Eos ut ipsum et.
      - Expedita asperiores et.
      - Ut quia ut commodi.
  BatchStatusResponseBody:
    title: BatchStatusResponseBody
    type: object
    properties:
      run_id:
        type: string
        example: Tempore nostrum aliquid fugiat optio consequatur.
      running:
        type: boolean
        example: true
      status:
        type: string
        example: Accusamus possimus fuga esse.
      workflow_id:
        type: string
        example: Aut itaque et.
    example:
      run_id: Enim fuga quam aut sit.
      running: true
      status: Corrupti veniam maiores ducimus in.
      workflow_id: Et laboriosam qui.
    required:
    - running
  BatchSubmitNotAvailableResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: submit_not_available_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BatchSubmitNotValidResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: submit_not_valid_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BatchSubmitRequestBody:
    title: BatchSubmitRequestBody
    type: object
    properties:
      completed_dir:
        type: string
        example: Sit sint est qui cum nihil quis.
      path:
        type: string
        example: Dolor quas corrupti.
      pipeline:
        type: string
        example: Cumque qui facilis omnis.
      processing_config:
        type: string
        example: Officia voluptate.
      retention_period:
        type: string
        example: Sit quibusdam quidem consectetur praesentium.
    example:
      completed_dir: Esse consectetur aut quis accusamus enim consequatur.
      path: Aperiam velit.
      pipeline: Nobis delectus.
      processing_config: Fuga omnis corporis et sunt.
      retention_period: Consequatur natus illum.
    required:
    - path
  BatchSubmitResponseBody:
    title: BatchSubmitResponseBody
    type: object
    properties:
      run_id:
        type: string
        example: Iste dolorem.
      workflow_id:
        type: string
        example: Est iure optio suscipit.
    example:
      run_id: Quidem aliquam fuga laborum maiores et.
      workflow_id: Maxime dicta.
    required:
    - workflow_id
    - run_id
  CollectionBulkNotAvailableResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: bulk_not_available_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionBulkNotValidResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: bulk_not_valid_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionBulkRequestBody:
    title: CollectionBulkRequestBody
    type: object
    properties:
      operation:
        type: string
        example: abandon
        enum:
        - retry
        - cancel
        - abandon
      size:
        type: integer
        default: 100
        example: 8206095306886416010
        format: int64
      status:
        type: string
        example: abandoned
        enum:
        - new
        - in progress
        - done
        - error
        - unknown
        - queued
        - pending
        - abandoned
    example:
      operation: cancel
      size: 18036125241233620415
      status: unknown
    required:
    - operation
    - status
  CollectionBulkResponseBody:
    title: CollectionBulkResponseBody
    type: object
    properties:
      run_id:
        type: string
        example: Consequatur facere omnis ab nihil magni.
      workflow_id:
        type: string
        example: Tenetur aut et occaecati harum.
    example:
      run_id: Quia fugiat quam iste velit explicabo.
      workflow_id: Consequatur aut adipisci doloribus quas sit vitae.
    required:
    - workflow_id
    - run_id
  CollectionBulkStatusResponseBody:
    title: CollectionBulkStatusResponseBody
    type: object
    properties:
      closed_at:
        type: string
        example: "2000-12-21T15:12:45Z"
        format: date-time
      run_id:
        type: string
        example: Magni mollitia et quod aut veritatis numquam.
      running:
        type: boolean
        example: false
      started_at:
        type: string
        example: "2015-02-11T18:18:46Z"
        format: date-time
      status:
        type: string
        example: Alias maxime architecto molestiae.
      workflow_id:
        type: string
        example: Assumenda explicabo adipisci.
    example:
      closed_at: "1990-07-24T22:49:26Z"
      run_id: Voluptatem laborum.
      running: true
      started_at: "2009-02-06T07:39:29Z"
      status: Atque culpa et earum et omnis et.
      workflow_id: Voluptatibus quibusdam quibusdam voluptatem non.
    required:
    - running
  CollectionCancelNotFoundResponseBody:
    title: CollectionCancelNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 951410389815766576
        format: int64
      message:
        type: string
        description: Message of error
        example: Architecto magnam asperiores tempora autem.
    description: Collection not found
    example:
      id: 7358593745880113932
      message: Aliquid consequatur.
    required:
    - message
    - id
  CollectionCancelNotRunningResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: cancel_not_running_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionDecideNotFoundResponseBody:
    title: CollectionDecideNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 15237653089904143505
        format: int64
      message:
        type: string
        description: Message of error
        example: Accusamus distinctio omnis qui.
    description: Collection not found
    example:
      id: 2610080554516588188
      message: Quia dolor ea.
    required:
    - message
    - id
  CollectionDecideNotValidResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: decide_not_valid_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionDeleteNotFoundResponseBody:
    title: CollectionDeleteNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 2691854561358134026
        format: int64
      message:
        type: string
        description: Message of error
        example: Consequuntur fuga nesciunt ullam quia et.
    description: Collection not found
    example:
      id: 8177308441370769
      message: Fugit amet facilis.
    required:
    - message
    - id
  CollectionDownloadNotFoundResponseBody:
    title: CollectionDownloadNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 7811120016112005653
        format: int64
      message:
        type: string
        description: Message of error
        example: Voluptatem et est tenetur vel assumenda natus.
    description: Collection not found
    example:
      id: 737223079499073311
      message: Nam aliquid quos.
    required:
    - message
    - id
  CollectionListResponseBody:
    title: CollectionListResponseBody
    type: object
    properties:
      items:
        $ref: '#/definitions/EnduroStoredCollectionResponseBodyCollection'
      next_cursor:
        type: string
        example: Cupiditate ipsam omnis voluptatem cum.
    example:
      items:
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      next_cursor: Voluptatem error adipisci vel rerum.
    required:
    - items
  CollectionMonitorResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.monitor-update; view=default'
    type: object
    properties:
      id:
        type: integer
        description: Identifier of collection
        example: 17512028379679435893
        format: int64
      item:
        $ref: '#/definitions/EnduroStoredCollectionResponseBody'
      type:
        type: string
        description: Type of the event
        example: Voluptatem beatae modi omnis voluptatem et.
    description: MonitorResponseBody result type (default view)
    example:
      id: 9151525906289518085
      item:
        aip_id: 0E0CB887-B526-812D-F285-DE018C555BB8
        completed_at: "1997-08-27T00:00:04Z"
        created_at: "1989-09-24T08:53:28Z"
        id: 4957819645449742263
        name: Labore totam harum repellat.
        original_id: Nostrum delectus dolor nisi.
        pipeline_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
        run_id: 0C589E55-99C1-3ED8-809A-1463C91242B6
        started_at: "1998-02-12T04:24:46Z"
        status: unknown
        transfer_id: AB12B85B-1864-53B4-4A92-3519B45D0D5E
        workflow_id: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
      type: Aliquam aliquid non tempore vel.
    required:
    - id
    - type
  CollectionRetryNotFoundResponseBody:
    title: CollectionRetryNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 14831543066782228698
        format: int64
      message:
        type: string
        description: Message of error
        example: Id ducimus.
    description: Collection not found
    example:
      id: 8000312645361077467
      message: Distinctio aspernatur tempora maxime omnis.
    required:
    - message
    - id
  CollectionRetryNotRunningResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: retry_not_running_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CollectionShowNotFoundResponseBody:
    title: CollectionShowNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 9835271868051980153
        format: int64
      message:
        type: string
        description: Message of error
        example: Ipsa dolor deserunt provident provident.
    description: Collection not found
    example:
      id: 6740760545696498930
      message: Exercitationem atque quo impedit non dicta culpa.
    required:
    - message
    - id
  CollectionShowResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.stored-collection; view=default'
    type: object
    properties:
      aip_id:
        type: string
        description: Identifier of Archivematica AIP
        example: 1883B2DF-F70A-5DB7-7F4C-C27752CD3BFF
        format: uuid
      completed_at:
        type: string
        description: Completion datetime
        example: "1995-07-06T21:57:28Z"
        format: date-time
      created_at:
        type: string
        description: Creation datetime
        example: "1982-12-23T00:51:34Z"
        format: date-time
      id:
        type: integer
        description: Identifier of collection
        example: 17557787113732579557
        format: int64
      name:
        type: string
        description: Name of the collection
        example: Qui numquam totam est.
      original_id:
        type: string
        description: Identifier provided by the client
        example: Quisquam sed sed hic in.
      pipeline_id:
        type: string
        description: Identifier of Archivematica pipeline
        example: EF5D214E-555E-4D58-0EF2-F45C1076AF15
        format: uuid
      run_id:
        type: string
        description: Identifier of latest processing workflow run
        example: ABE8488E-AFF1-4B36-A260-952A5B020283
        format: uuid
      started_at:
        type: string
        description: Start datetime
        example: "1977-11-02T07:18:21Z"
        format: date-time
      status:
        type: string
        description: Status of the collection
        default: new
        example: error
        enum:
        - new
        - in progress
        - done
        - error
        - unknown
        - queued
        - pending
        - abandoned
      transfer_id:
        type: string
        description: Identifier of Archivematica transfer
        example: FA72E36A-FA51-C026-0A9C-7A8A45F95FF4
        format: uuid
      workflow_id:
        type: string
        description: Identifier of processing workflow
        example: 27C5C26D-4373-5EA2-93BA-5BC74245EFE2
        format: uuid
    description: ShowResponseBody result type (default view)
    example:
      aip_id: 19ED6A1B-CD96-F1FD-8091-A91B19FDFE53
      completed_at: "1998-11-15T13:24:26Z"
      created_at: "1995-01-01T19:38:07Z"
      id: 16726981500754704734
      name: In laudantium vero sit debitis.
      original_id: Facere molestiae et sunt.
      pipeline_id: E096A0A7-535D-C37F-3DCD-E8ACD632C8D1
      run_id: 1B191706-6645-37C2-12DA-6685EFB4287D
      started_at: "1987-02-13T19:42:16Z"
      status: unknown
      transfer_id: 58984EF0-C2B3-2A7F-DD1D-A40333BD45D9
      workflow_id: 4C17A184-FC45-FB3A-5AE0-6E4A3706BA95
    required:
    - id
    - status
    - created_at
  CollectionWorkflowNotFoundResponseBody:
    title: CollectionWorkflowNotFoundResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Identifier of missing collection
        example: 16822297729379021847
        format: int64
      message:
        type: string
        description: Message of error
        example: Autem a a odit architecto quisquam nisi.
    description: Collection not found
    example:
      id: 10870541205377463360
      message: Autem et.
    required:
    - message
    - id
  CollectionWorkflowResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.collection-workflow-status;
      view=default'
    type: object
    properties:
      history:
        $ref: '#/definitions/EnduroCollectionWorkflowHistoryResponseBodyCollection'
      status:
        type: string
        example: Voluptatum necessitatibus non cum earum quis.
    description: WorkflowResponseBody result type (default view)
    example:
      history:
      - details: Ut eveniet et rerum nemo corporis.
        id: 9720827093168823906
        type: Omnis doloremque sint dolorum quasi ex labore.
      - details: Ut eveniet et rerum nemo corporis.
        id: 9720827093168823906
        type: Omnis doloremque sint dolorum quasi ex labore.
      - details: Ut eveniet et rerum nemo corporis.
        id: 9720827093168823906
        type: Omnis doloremque sint dolorum quasi ex labore.
      - details: Ut eveniet et rerum nemo corporis.
        id: 9720827093168823906
        type: Omnis doloremque sint dolorum quasi ex labore.
      status: Aut omnis iusto modi quis distinctio.
  EarkStatusResponseBody:
    title: EarkStatusResponseBody
    type: object
    properties:
      run_id:
        type: string
        example: Qui et id.
      running:
        type: boolean
        example: false
      status:
        type: string
        example: Quidem voluptatum aut quia recusandae architecto.
      workflow_id:
        type: string
        example: Qui excepturi iste aperiam laborum suscipit aut.
    example:
      run_id: Consectetur est sit exercitationem.
      running: true
      status: Possimus vero.
      workflow_id: Omnis praesentium modi cum illum id.
    required:
    - running
  EarkSubmitNotAvailableResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: submit_not_available_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  EarkSubmitNotValidResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: submit_not_valid_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  EarkSubmitResponseBody:
    title: EarkSubmitResponseBody
    type: object
    properties:
      run_id:
        type: string
        example: Ipsum qui quisquam ad aut.
      workflow_id:
        type: string
        example: Aspernatur ut dolorem sint dolor officiis.
    example:
      run_id: Temporibus officiis labore.
      workflow_id: Itaque voluptas provident harum quia ab ducimus.
    required:
    - workflow_id
    - run_id
  EnduroCollectionWorkflowHistoryResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.collection-workflow-history;
      view=default'
    type: object
    properties:
      details:
        description: Contents of the event
        example: Voluptatum quibusdam.
      id:
        type: integer
        description: Identifier of collection
        example: 3054458866920097073
        format: int64
      type:
        type: string
        description: Type of the event
        example: Id quasi dolor veritatis voluptatem.
    description: WorkflowHistoryEvent describes a history event in Cadence. (default
      view)
    example:
      details: Est aut explicabo perferendis sunt quas.
      id: 5532165772958537512
      type: Animi praesentium.
  EnduroCollectionWorkflowHistoryResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.enduro.collection-workflow-history;
      type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/EnduroCollectionWorkflowHistoryResponseBody'
    description: EnduroCollection-Workflow-HistoryCollectionResponseBody is the result
      type for an array of EnduroCollection-Workflow-HistoryResponseBody (default
      view)
    example:
    - details: Ut eveniet et rerum nemo corporis.
      id: 9720827093168823906
      type: Omnis doloremque sint dolorum quasi ex labore.
    - details: Ut eveniet et rerum nemo corporis.
      id: 9720827093168823906
      type: Omnis doloremque sint dolorum quasi ex labore.
  EnduroStoredCollectionResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.stored-collection; view=default'
    type: object
    properties:
      aip_id:
        type: string
        description: Identifier of Archivematica AIP
        example: C14F18CD-9DAC-4197-F250-EC3FBAFE81DD
        format: uuid
      completed_at:
        type: string
        description: Completion datetime
        example: "1970-10-15T00:03:22Z"
        format: date-time
      created_at:
        type: string
        description: Creation datetime
        example: "2007-04-29T00:55:57Z"
        format: date-time
      id:
        type: integer
        description: Identifier of collection
        example: 12195178451962438920
        format: int64
      name:
        type: string
        description: Name of the collection
        example: At est excepturi dignissimos.
      original_id:
        type: string
        description: Identifier provided by the client
        example: Quis iure.
      pipeline_id:
        type: string
        description: Identifier of Archivematica pipeline
        example: 0866BAED-0A78-C310-5523-F8F1C3A1D14C
        format: uuid
      run_id:
        type: string
        description: Identifier of latest processing workflow run
        example: EBC096AD-D9EC-2F9C-CCD5-2819684939D3
        format: uuid
      started_at:
        type: string
        description: Start datetime
        example: "1978-05-27T01:41:50Z"
        format: date-time
      status:
        type: string
        description: Status of the collection
        default: new
        example: done
        enum:
        - new
        - in progress
        - done
        - error
        - unknown
        - queued
        - pending
        - abandoned
      transfer_id:
        type: string
        description: Identifier of Archivematica transfer
        example: 36111869-D7E7-159A-3E5F-AC3C2E0C42DD
        format: uuid
      workflow_id:
        type: string
        description: Identifier of processing workflow
        example: D16B2ED1-3971-5178-0135-F3E819F3BA4F
        format: uuid
    description: StoredCollection describes a collection retrieved by the service.
      (default view)
    example:
      aip_id: 45442A02-3FD6-C827-BA11-864B7D92257A
      completed_at: "1977-12-10T11:31:25Z"
      created_at: "1999-04-24T03:56:53Z"
      id: 10895205645452708913
      name: Est voluptate quis sunt.
      original_id: Velit nisi dolorum inventore.
      pipeline_id: 2E7D48F1-CD94-6874-B6D8-717D4A8FD873
      run_id: 3E620E27-EED0-3E38-87CD-C7C87D512815
      started_at: "1989-12-22T07:05:18Z"
      status: in progress
      transfer_id: BD3BFBE7-02F2-99D7-D026-8BD77E75C122
      workflow_id: 84858054-1B69-3E9A-C82B-BF11FF33B1D8
    required:
    - id
    - status
    - created_at
  EnduroStoredCollectionResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.enduro.stored-collection; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/EnduroStoredCollectionResponseBody'
    description: EnduroStored-CollectionCollectionResponseBody is the result type
      for an array of EnduroStored-CollectionResponseBody (default view)
    example:
    - aip_id: 0E0CB887-B526-812D-F285-DE018C555BB8
      completed_at: "1997-08-27T00:00:04Z"
      created_at: "1989-09-24T08:53:28Z"
      id: 4957819645449742263
      name: Labore totam harum repellat.
      original_id: Nostrum delectus dolor nisi.
      pipeline_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
      run_id: 0C589E55-99C1-3ED8-809A-1463C91242B6
      started_at: "1998-02-12T04:24:46Z"
      status: unknown
      transfer_id: AB12B85B-1864-53B4-4A92-3519B45D0D5E
      workflow_id: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
    - aip_id: 0E0CB887-B526-812D-F285-DE018C555BB8
      completed_at: "1997-08-27T00:00:04Z"
      created_at: "1989-09-24T08:53:28Z"
      id: 4957819645449742263
      name: Labore totam harum repellat.
      original_id: Nostrum delectus dolor nisi.
      pipeline_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
      run_id: 0C589E55-99C1-3ED8-809A-1463C91242B6
      started_at: "1998-02-12T04:24:46Z"
      status: unknown
      transfer_id: AB12B85B-1864-53B4-4A92-3519B45D0D5E
      workflow_id: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
    - aip_id: 0E0CB887-B526-812D-F285-DE018C555BB8
      completed_at: "1997-08-27T00:00:04Z"
      created_at: "1989-09-24T08:53:28Z"
      id: 4957819645449742263
      name: Labore totam harum repellat.
      original_id: Nostrum delectus dolor nisi.
      pipeline_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
      run_id: 0C589E55-99C1-3ED8-809A-1463C91242B6
      started_at: "1998-02-12T04:24:46Z"
      status: unknown
      transfer_id: AB12B85B-1864-53B4-4A92-3519B45D0D5E
      workflow_id: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
    - aip_id: 0E0CB887-B526-812D-F285-DE018C555BB8
      completed_at: "1997-08-27T00:00:04Z"
      created_at: "1989-09-24T08:53:28Z"
      id: 4957819645449742263
      name: Labore totam harum repellat.
      original_id: Nostrum delectus dolor nisi.
      pipeline_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
      run_id: 0C589E55-99C1-3ED8-809A-1463C91242B6
      started_at: "1998-02-12T04:24:46Z"
      status: unknown
      transfer_id: AB12B85B-1864-53B4-4A92-3519B45D0D5E
      workflow_id: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
  EnduroStoredPipelineResponse:
    title: 'Mediatype identifier: application/vnd.enduro.stored-pipeline; view=default'
    type: object
    properties:
      capacity:
        type: integer
        description: Maximum concurrent transfers
        example: 2530439535807859749
        format: int64
      current:
        type: integer
        description: Current transfers
        example: 5707507152436743067
        format: int64
      id:
        type: string
        description: Identifier of the pipeline
        example: 73C3FFFF-5E99-6BB1-43A8-61CBFDE01330
        format: uuid
      name:
        type: string
        description: Name of the pipeline
        example: Et magni consequuntur.
    description: StoredPipeline describes a pipeline retrieved by this service. (default
      view)
    example:
      capacity: 1857366314510706938
      current: 6412453802971423915
      id: 9CEC8109-7649-F74C-CDA6-D8C4434F6E6F
      name: Tenetur quibusdam rerum sit labore.
    required:
    - name
  PipelineProcessingNotFoundResponseBody:
    title: PipelineProcessingNotFoundResponseBody
    type: object
    properties:
      id:
        type: string
        description: Identifier of missing pipeline
        example: Fugiat a officiis ipsum.
      message:
        type: string
        description: Message of error
        example: Et et eligendi voluptatem.
    description: Pipeline not found
    example:
      id: Qui rerum asperiores qui.
      message: Necessitatibus voluptas mollitia dolore.
    required:
    - message
    - id
  PipelineShowNotFoundResponseBody:
    title: PipelineShowNotFoundResponseBody
    type: object
    properties:
      id:
        type: string
        description: Identifier of missing pipeline
        example: Praesentium sunt ut.
      message:
        type: string
        description: Message of error
        example: Facilis magnam a veritatis vel.
    description: Pipeline not found
    example:
      id: Voluptates nulla autem et perspiciatis libero voluptas.
      message: Illum illum tenetur.
    required:
    - message
    - id
  PipelineShowResponseBody:
    title: 'Mediatype identifier: application/vnd.enduro.stored-pipeline; view=default'
    type: object
    properties:
      capacity:
        type: integer
        description: Maximum concurrent transfers
        example: 1270080036653766538
        format: int64
      current:
        type: integer
        description: Current transfers
        example: 3460011645440185538
        format: int64
      id:
        type: string
        description: Identifier of the pipeline
        example: FDCA5323-C4C9-FB10-0E70-1125891ABDEE
        format: uuid
      name:
        type: string
        description: Name of the pipeline
        example: Ut tenetur dolorum error aut quibusdam.
    description: ShowResponseBody result type (default view)
    example:
      capacity: 4816212125257195638
      current: 5231338353180703567
      id: B79E857E-CE20-97AA-CE10-8106502AEA86
      name: Non unde ut aspernatur.
    required:
    - name
