openapi: 3.0.3
info:
  title: Enduro API
  version: "1.0"
servers:
- url: http://localhost:9000
paths:
  /batch:
    get:
      tags:
      - batch
      summary: status batch
      description: Retrieve status of current batch operation.
      operationId: batch#status
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchStatusResult'
              example:
                run_id: Vel sint ducimus officia labore eius qui.
                running: true
                status: Nam sed nostrum enim laborum ea facilis.
                workflow_id: Dolor illum excepturi magni quidem.
    post:
      tags:
      - batch
      summary: submit batch
      description: Submit a new batch
      operationId: batch#submit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRequestBody'
            example:
              completed_dir: Laboriosam odit.
              path: Sit nihil.
              pipeline: Necessitatibus vel aut deleniti quia qui.
              processing_config: Vel voluptatem.
              retention_period: Sed perferendis illum illum omnis et officiis.
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResult'
              example:
                run_id: Debitis rerum.
                workflow_id: Velit possimus et ea aut harum.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "409":
          description: Conflict response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /batch/hints:
    get:
      tags:
      - batch
      summary: hints batch
      description: Retrieve form hints
      operationId: batch#hints
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchHintsResult'
              example:
                completed_dirs:
                - Impedit vero ducimus.
                - Quo illo natus et.
                - Eaque suscipit in cum et quia facere.
                - Doloribus sed tempore voluptatum quo.
  /collection:
    get:
      tags:
      - collection
      summary: list collection
      description: List all stored collections
      operationId: collection#list
      parameters:
      - name: name
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Aut consequatur enim.
        example: Qui et et et voluptas perspiciatis ullam.
      - name: original_id
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Similique vero ratione deserunt maxime et aut.
        example: Ut aut sunt rem voluptatem voluptate distinctio.
      - name: transfer_id
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: 911E76DE-4702-489B-4E65-C8542C813C48
          format: uuid
        example: B6C43FB7-3F0C-5200-5A8D-F20ADE09BC16
      - name: aip_id
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: 829FA833-90F0-ADA3-B91B-13E44809B08B
          format: uuid
        example: 72FD3E1D-3307-706F-0CB2-70D36C298204
      - name: pipeline_id
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: FA7FF8A2-BD57-D275-C428-6ADDFE33156A
          format: uuid
        example: D7D3C5B2-4DBE-653E-AE0D-8BCD9B31C1A9
      - name: earliest_created_time
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: "2006-09-23T11:31:55Z"
          format: date-time
        example: "1999-12-17T11:47:57Z"
      - name: latest_created_time
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: "2014-10-13T03:53:49Z"
          format: date-time
        example: "1975-02-02T01:08:46Z"
      - name: status
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: abandoned
          enum:
          - new
          - in progress
          - done
          - error
          - unknown
          - queued
          - pending
          - abandoned
        example: unknown
      - name: cursor
        in: query
        description: Pagination cursor
        allowEmptyValue: true
        schema:
          type: string
          description: Pagination cursor
          example: Saepe reiciendis quia.
        example: Odit ab.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseBody'
              example:
                items:
                - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
                  completed_at: "2014-01-26T22:52:33Z"
                  created_at: "2006-09-07T19:48:15Z"
                  id: 5273261262554249024
                  name: Iusto laudantium assumenda.
                  original_id: Voluptatem eum et rerum.
                  pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1986-05-13T23:32:21Z"
                  status: unknown
                  transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
                  completed_at: "2014-01-26T22:52:33Z"
                  created_at: "2006-09-07T19:48:15Z"
                  id: 5273261262554249024
                  name: Iusto laudantium assumenda.
                  original_id: Voluptatem eum et rerum.
                  pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1986-05-13T23:32:21Z"
                  status: unknown
                  transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
                  completed_at: "2014-01-26T22:52:33Z"
                  created_at: "2006-09-07T19:48:15Z"
                  id: 5273261262554249024
                  name: Iusto laudantium assumenda.
                  original_id: Voluptatem eum et rerum.
                  pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1986-05-13T23:32:21Z"
                  status: unknown
                  transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
                  completed_at: "2014-01-26T22:52:33Z"
                  created_at: "2006-09-07T19:48:15Z"
                  id: 5273261262554249024
                  name: Iusto laudantium assumenda.
                  original_id: Voluptatem eum et rerum.
                  pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1986-05-13T23:32:21Z"
                  status: unknown
                  transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                next_cursor: Ad aut rerum.
  /collection/{id}:
    delete:
      tags:
      - collection
      summary: delete collection
      description: Delete collection by ID
      operationId: collection#delete
      parameters:
      - name: id
        in: path
        description: Identifier of collection to delete
        required: true
        schema:
          type: integer
          description: Identifier of collection to delete
          example: 14015877184925223068
        example: 14000398021582865133
      responses:
        "204":
          description: No Content response.
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 6101152394700680766
                message: Fugit et porro suscipit.
    get:
      tags:
      - collection
      summary: show collection
      description: Show collection by ID
      operationId: collection#show
      parameters:
      - name: id
        in: path
        description: Identifier of collection to show
        required: true
        schema:
          type: integer
          description: Identifier of collection to show
          example: 10449308666159982787
        example: 6284991016880369083
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroStoredCollection'
              example:
                aip_id: EA2D3703-2B9D-E7C0-35B9-DB753C364369
                completed_at: "2000-10-04T09:57:15Z"
                created_at: "2010-07-22T22:55:51Z"
                id: 12024565834601469556
                name: Quam quas.
                original_id: Et consequatur aut enim consequuntur debitis temporibus.
                pipeline_id: 9A05BD8A-CA8D-335E-C26E-14DB8FEBAB04
                run_id: E058AD50-5D7F-E9A8-E010-D33044724992
                started_at: "2014-07-31T20:44:18Z"
                status: queued
                transfer_id: E31B6C92-4A10-2D9D-2B43-B3362900308F
                workflow_id: F25C441B-B3AA-5871-1077-53EACA084D5A
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 1094484444001815440
                message: Praesentium et nam.
  /collection/{id}/cancel:
    post:
      tags:
      - collection
      summary: cancel collection
      description: Cancel collection processing by ID
      operationId: collection#cancel
      parameters:
      - name: id
        in: path
        description: Identifier of collection to remove
        required: true
        schema:
          type: integer
          description: Identifier of collection to remove
          example: 14046503965744569793
        example: 16808961171026815943
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 5550828451059843862
                message: At velit quod et maxime quia.
  /collection/{id}/decision:
    post:
      tags:
      - collection
      summary: decide collection
      description: Make decision for a pending collection by ID
      operationId: collection#decide
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        schema:
          type: integer
          description: Identifier of collection to look up
          example: 2977694798359306634
        example: 10819156414999815177
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                option:
                  type: string
                  description: Decision option to proceed with
                  example: Ea doloremque odio non facere sint.
              example:
                option: Repudiandae expedita suscipit.
            example:
              option: Consequatur voluptates.
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 473759361842336147
                message: Eos eius officiis rerum.
  /collection/{id}/download:
    get:
      tags:
      - collection
      summary: download collection
      description: Download collection by ID
      operationId: collection#download
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        schema:
          type: integer
          description: Identifier of collection to look up
          example: 14111731765164234935
        example: 9919332922021134491
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example:
                - 77
                - 97
                - 120
                - 105
                - 109
                - 101
                - 32
                - 101
                - 120
                - 32
                - 101
                - 116
                - 32
                - 97
                - 115
                - 112
                - 101
                - 114
                - 110
                - 97
                - 116
                - 117
                - 114
                - 32
                - 109
                - 111
                - 108
                - 101
                - 115
                - 116
                - 105
                - 97
                - 115
                - 32
                - 100
                - 105
                - 99
                - 116
                - 97
                - 32
                - 115
                - 105
                - 116
                - 46
                format: binary
              example:
              - 81
              - 117
              - 105
              - 32
              - 105
              - 100
              - 32
              - 111
              - 112
              - 116
              - 105
              - 111
              - 32
              - 111
              - 102
              - 102
              - 105
              - 99
              - 105
              - 105
              - 115
              - 32
              - 101
              - 115
              - 116
              - 32
              - 102
              - 97
              - 99
              - 101
              - 114
              - 101
              - 46
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 7264703909707707120
                message: Voluptate et incidunt laboriosam mollitia recusandae.
  /collection/{id}/retry:
    post:
      tags:
      - collection
      summary: retry collection
      description: Retry collection processing by ID
      operationId: collection#retry
      parameters:
      - name: id
        in: path
        description: Identifier of collection to retry
        required: true
        schema:
          type: integer
          description: Identifier of collection to retry
          example: 13486688006492880610
        example: 140126741329145784
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 1862234972514153970
                message: Aut dolorem perspiciatis repudiandae.
  /collection/{id}/workflow:
    get:
      tags:
      - collection
      summary: workflow collection
      description: Retrieve workflow status by ID
      operationId: collection#workflow
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        schema:
          type: integer
          description: Identifier of collection to look up
          example: 17300977468732700225
        example: 11075052354019889469
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroCollectionWorkflowStatus'
              example:
                history:
                - details: In quis sed.
                  id: 2015423930972900414
                  type: Enim esse aut accusantium deleniti beatae voluptas.
                - details: In quis sed.
                  id: 2015423930972900414
                  type: Enim esse aut accusantium deleniti beatae voluptas.
                - details: In quis sed.
                  id: 2015423930972900414
                  type: Enim esse aut accusantium deleniti beatae voluptas.
                - details: In quis sed.
                  id: 2015423930972900414
                  type: Enim esse aut accusantium deleniti beatae voluptas.
                status: Qui dolor.
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 7490280638703895590
                message: Fugiat officia repellat.
  /collection/bulk:
    get:
      tags:
      - collection
      summary: bulk_status collection
      description: Retrieve status of current bulk operation.
      operationId: collection#bulk_status
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkStatusResult'
              example:
                closed_at: "1983-11-09T08:33:50Z"
                run_id: Officiis eum pariatur.
                running: false
                started_at: "2006-08-01T01:39:09Z"
                status: Repellat architecto dolore harum.
                workflow_id: Excepturi dolor aut rerum.
    post:
      tags:
      - collection
      summary: bulk collection
      description: Bulk operations (retry, cancel...).
      operationId: collection#bulk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkRequestBody'
            example:
              operation: cancel
              size: 15492129042979125718
              status: in progress
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResult'
              example:
                run_id: Deserunt illum et tempora.
                workflow_id: Explicabo et numquam aut dolores et voluptas.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "409":
          description: Conflict response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /collection/monitor:
    get:
      tags:
      - collection
      summary: monitor collection
      operationId: collection#monitor
      responses:
        "101":
          description: Switching Protocols response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroMonitorUpdate'
              example:
                id: 2293355532387428117
                item:
                  aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
                  completed_at: "2014-01-26T22:52:33Z"
                  created_at: "2006-09-07T19:48:15Z"
                  id: 5273261262554249024
                  name: Iusto laudantium assumenda.
                  original_id: Voluptatem eum et rerum.
                  pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1986-05-13T23:32:21Z"
                  status: unknown
                  transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                type: Deleniti ea tenetur deleniti.
  /eark:
    get:
      tags:
      - eark
      summary: status eark
      description: Retrieve status of current eark operation.
      operationId: eark#status
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchStatusResult'
              example:
                run_id: Voluptas iusto sit vitae ad quasi.
                running: true
                status: Officiis eaque.
                workflow_id: Magnam pariatur.
    post:
      tags:
      - eark
      summary: submit eark
      description: Submit a new eark
      operationId: eark#submit
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResult'
              example:
                run_id: Et et repellendus quam.
                workflow_id: Eaque nemo quia.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "409":
          description: Conflict response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /pipeline:
    get:
      tags:
      - pipeline
      summary: list pipeline
      description: List all known pipelines
      operationId: pipeline#list
      parameters:
      - name: name
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Sequi aliquam.
        example: Quam rerum ut qui et quas.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnduroStoredPipeline'
                example:
                - capacity: 2813017700037192781
                  current: 2555592761769951567
                  id: 95545D09-3153-0F17-09F7-7FEB1545D780
                  name: Aspernatur quas.
                - capacity: 2813017700037192781
                  current: 2555592761769951567
                  id: 95545D09-3153-0F17-09F7-7FEB1545D780
                  name: Aspernatur quas.
                - capacity: 2813017700037192781
                  current: 2555592761769951567
                  id: 95545D09-3153-0F17-09F7-7FEB1545D780
                  name: Aspernatur quas.
                - capacity: 2813017700037192781
                  current: 2555592761769951567
                  id: 95545D09-3153-0F17-09F7-7FEB1545D780
                  name: Aspernatur quas.
              example:
              - capacity: 2813017700037192781
                current: 2555592761769951567
                id: 95545D09-3153-0F17-09F7-7FEB1545D780
                name: Aspernatur quas.
              - capacity: 2813017700037192781
                current: 2555592761769951567
                id: 95545D09-3153-0F17-09F7-7FEB1545D780
                name: Aspernatur quas.
              - capacity: 2813017700037192781
                current: 2555592761769951567
                id: 95545D09-3153-0F17-09F7-7FEB1545D780
                name: Aspernatur quas.
  /pipeline/{id}:
    get:
      tags:
      - pipeline
      summary: show pipeline
      description: Show pipeline by ID
      operationId: pipeline#show
      parameters:
      - name: id
        in: path
        description: Identifier of pipeline to show
        required: true
        schema:
          type: string
          description: Identifier of pipeline to show
          example: 46F6C162-49C8-C44E-0535-1AE5567F50BB
          format: uuid
        example: ECE21E30-A47C-B7C4-02DC-7EE3E791AD18
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroStoredPipeline'
              example:
                capacity: 397709581822181909
                current: 8055235019801166035
                id: 8B791A71-1C43-AB9B-4366-12192353E1A2
                name: Quam assumenda saepe omnis et eius.
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineNotFound'
              example:
                id: Tenetur incidunt quia placeat minus nobis.
                message: Est est ut voluptatem voluptatem numquam.
  /pipeline/{id}/processing:
    get:
      tags:
      - pipeline
      summary: processing pipeline
      description: List all processing configurations of a pipeline given its ID
      operationId: pipeline#processing
      parameters:
      - name: id
        in: path
        description: Identifier of pipeline
        required: true
        schema:
          type: string
          description: Identifier of pipeline
          example: F580252C-B3AF-DABD-2F2F-135B48131375
          format: uuid
        example: 9FCDD0FB-0528-5E6A-D5F3-4F00120EB522
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Aliquam quo similique ipsa voluptatum tempore voluptatum.
                example:
                - Omnis est ut ad temporibus.
                - Repellat est libero maxime.
                - Consectetur consequuntur eum provident accusamus voluptatem.
              example:
              - Repellendus maiores et minus reprehenderit nobis ratione.
              - Debitis labore autem molestias repellendus.
              - Eaque ut magni dolorem minus ut.
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineNotFound'
              example:
                id: Ab consectetur.
                message: Fugit ipsam.
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download internal/api/gen/http/openapi.json
      description: JSON document containing the API swagger definition.
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    BatchHintsResult:
      type: object
      properties:
        completed_dirs:
          type: array
          items:
            type: string
            example: In qui.
          description: A list of known values of completedDir used by existing watchers.
          example:
          - Quia asperiores et excepturi placeat.
          - Sunt debitis dolorum quia ea modi culpa.
      example:
        completed_dirs:
        - Unde atque est.
        - Quaerat qui alias minima odio laboriosam.
        - Pariatur ipsam velit consequatur.
        - Tempore necessitatibus quas.
    BatchResult:
      type: object
      properties:
        run_id:
          type: string
          example: Consequuntur aliquam culpa facere aliquid perspiciatis.
        workflow_id:
          type: string
          example: Aperiam praesentium voluptatum delectus commodi ea non.
      example:
        run_id: Quia aperiam saepe quos.
        workflow_id: Est optio repellendus molestias consequatur mollitia aut.
      required:
      - workflow_id
      - run_id
    BatchStatusResult:
      type: object
      properties:
        run_id:
          type: string
          example: Et cumque eius.
        running:
          type: boolean
          example: true
        status:
          type: string
          example: Cupiditate expedita distinctio qui.
        workflow_id:
          type: string
          example: Dolor labore quis aut sint recusandae eum.
      example:
        run_id: Ducimus aspernatur.
        running: true
        status: Hic et cupiditate.
        workflow_id: Quia ducimus est consequuntur.
      required:
      - running
    BulkRequestBody:
      type: object
      properties:
        operation:
          type: string
          example: cancel
          enum:
          - retry
          - cancel
          - abandon
        size:
          type: integer
          default: 100
          example: 6558591797934287178
        status:
          type: string
          example: abandoned
          enum:
          - new
          - in progress
          - done
          - error
          - unknown
          - queued
          - pending
          - abandoned
      example:
        operation: cancel
        size: 9538887374092355
        status: pending
      required:
      - operation
      - status
    BulkStatusResult:
      type: object
      properties:
        closed_at:
          type: string
          example: "1980-10-31T01:01:41Z"
          format: date-time
        run_id:
          type: string
          example: Sed corrupti non non et id voluptas.
        running:
          type: boolean
          example: false
        started_at:
          type: string
          example: "1975-01-25T07:25:55Z"
          format: date-time
        status:
          type: string
          example: In eaque id qui inventore.
        workflow_id:
          type: string
          example: Minus ratione velit magni.
      example:
        closed_at: "1991-07-21T00:28:40Z"
        run_id: Sit minus repellat inventore culpa qui sapiente.
        running: true
        started_at: "1996-11-03T23:19:56Z"
        status: Quia repudiandae dolores qui.
        workflow_id: Est provident sint at modi est.
      required:
      - running
    CollectionNotfound:
      type: object
      properties:
        id:
          type: integer
          description: Identifier of missing collection
          example: 10356219786948220765
        message:
          type: string
          description: Message of error
          example: Earum neque est eaque ipsam.
      description: Collection not found
      example:
        id: 3681346159278483495
        message: Molestias ut earum aut in non.
      required:
      - message
      - id
    EnduroCollectionWorkflowHistory:
      type: object
      properties:
        details:
          type: string
          description: Contents of the event
          example: Enim dolorem quibusdam assumenda sit sed suscipit.
          format: binary
        id:
          type: integer
          description: Identifier of collection
          example: 8005296902049769923
        type:
          type: string
          description: Type of the event
          example: Corporis quisquam et.
      description: WorkflowHistoryEvent describes a history event in Cadence.
      example:
        details: Placeat dolorem in saepe.
        id: 14549228005944556233
        type: Aperiam architecto magnam.
    EnduroCollectionWorkflowHistoryCollection:
      type: array
      items:
        $ref: '#/components/schemas/EnduroCollectionWorkflowHistory'
      example:
      - details: In quis sed.
        id: 2015423930972900414
        type: Enim esse aut accusantium deleniti beatae voluptas.
      - details: In quis sed.
        id: 2015423930972900414
        type: Enim esse aut accusantium deleniti beatae voluptas.
    EnduroCollectionWorkflowStatus:
      type: object
      properties:
        history:
          $ref: '#/components/schemas/EnduroCollectionWorkflowHistoryCollection'
        status:
          type: string
          example: Quidem ut sit vitae.
      example:
        history:
        - details: In quis sed.
          id: 2015423930972900414
          type: Enim esse aut accusantium deleniti beatae voluptas.
        - details: In quis sed.
          id: 2015423930972900414
          type: Enim esse aut accusantium deleniti beatae voluptas.
        - details: In quis sed.
          id: 2015423930972900414
          type: Enim esse aut accusantium deleniti beatae voluptas.
        - details: In quis sed.
          id: 2015423930972900414
          type: Enim esse aut accusantium deleniti beatae voluptas.
        status: Expedita consequatur eaque ad.
    EnduroMonitorUpdate:
      type: object
      properties:
        id:
          type: integer
          description: Identifier of collection
          example: 7432705857453340995
        item:
          $ref: '#/components/schemas/EnduroStoredCollection'
        type:
          type: string
          description: Type of the event
          example: Et ipsum dicta numquam quae occaecati in.
      example:
        id: 10768096597688358347
        item:
          aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
          completed_at: "2014-01-26T22:52:33Z"
          created_at: "2006-09-07T19:48:15Z"
          id: 5273261262554249024
          name: Iusto laudantium assumenda.
          original_id: Voluptatem eum et rerum.
          pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1986-05-13T23:32:21Z"
          status: unknown
          transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        type: Ullam dolorem nulla quod sed fuga ipsam.
      required:
      - id
      - type
    EnduroStoredCollection:
      type: object
      properties:
        aip_id:
          type: string
          description: Identifier of Archivematica AIP
          example: AFBCBB7C-8004-B611-B6FD-506A7ADD07B4
          format: uuid
        completed_at:
          type: string
          description: Completion datetime
          example: "2008-02-07T20:33:01Z"
          format: date-time
        created_at:
          type: string
          description: Creation datetime
          example: "1990-10-21T22:11:11Z"
          format: date-time
        id:
          type: integer
          description: Identifier of collection
          example: 8873681488540165270
        name:
          type: string
          description: Name of the collection
          example: Consequatur vitae.
        original_id:
          type: string
          description: Identifier provided by the client
          example: At nam nesciunt.
        pipeline_id:
          type: string
          description: Identifier of Archivematica pipeline
          example: 7C2D3996-7ECF-5E12-276F-CE1436D6FAC3
          format: uuid
        run_id:
          type: string
          description: Identifier of latest processing workflow run
          example: 027F6A13-2527-4BB7-A500-146C0F61C2A5
          format: uuid
        started_at:
          type: string
          description: Start datetime
          example: "1977-08-07T01:23:02Z"
          format: date-time
        status:
          type: string
          description: Status of the collection
          default: new
          example: error
          enum:
          - new
          - in progress
          - done
          - error
          - unknown
          - queued
          - pending
          - abandoned
        transfer_id:
          type: string
          description: Identifier of Archivematica transfer
          example: 9FE8C952-2C90-CD7E-731A-C120E7B1B6ED
          format: uuid
        workflow_id:
          type: string
          description: Identifier of processing workflow
          example: 369C6341-CBF4-32C5-3AB9-B7CDCB864A1F
          format: uuid
      description: StoredCollection describes a collection retrieved by the service.
      example:
        aip_id: 0D4C4E5D-CCD2-045B-C43A-CA2A12989890
        completed_at: "1974-09-26T20:55:59Z"
        created_at: "2001-07-28T02:08:51Z"
        id: 18016512966141588580
        name: Nihil et.
        original_id: Non enim culpa laudantium veniam.
        pipeline_id: 13E08C6E-20ED-E692-75AF-CC5685A5CDC1
        run_id: 495DB94F-824E-E732-0B4B-502305E4ABA4
        started_at: "1981-11-29T00:41:52Z"
        status: done
        transfer_id: 07B1A7F6-0BFE-D016-9174-27BFC402D03B
        workflow_id: 2AFA4466-554C-3755-3A53-AAE48068F107
      required:
      - id
      - status
      - created_at
    EnduroStoredCollectionCollection:
      type: array
      items:
        $ref: '#/components/schemas/EnduroStoredCollection'
      example:
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
        completed_at: "2014-01-26T22:52:33Z"
        created_at: "2006-09-07T19:48:15Z"
        id: 5273261262554249024
        name: Iusto laudantium assumenda.
        original_id: Voluptatem eum et rerum.
        pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1986-05-13T23:32:21Z"
        status: unknown
        transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
    EnduroStoredPipeline:
      type: object
      properties:
        capacity:
          type: integer
          description: Maximum concurrent transfers
          example: 7064345608847404534
          format: int64
        current:
          type: integer
          description: Current transfers
          example: 3724634741641145487
          format: int64
        id:
          type: string
          description: Identifier of the pipeline
          example: 03F4110E-C4A6-ECD1-6EE0-B074CA2B3425
          format: uuid
        name:
          type: string
          description: Name of the pipeline
          example: Quod vitae.
      description: StoredPipeline describes a pipeline retrieved by this service.
      example:
        capacity: 6564036117872492517
        current: 7685341162099986570
        id: D27B2E95-C7AA-5857-EDCE-8F7D36361F87
        name: Enim amet architecto non repudiandae.
      required:
      - name
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    ListResponseBody:
      type: object
      properties:
        items:
          $ref: '#/components/schemas/EnduroStoredCollectionCollection'
        next_cursor:
          type: string
          example: Adipisci magnam animi adipisci debitis.
      example:
        items:
        - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
          completed_at: "2014-01-26T22:52:33Z"
          created_at: "2006-09-07T19:48:15Z"
          id: 5273261262554249024
          name: Iusto laudantium assumenda.
          original_id: Voluptatem eum et rerum.
          pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1986-05-13T23:32:21Z"
          status: unknown
          transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
          completed_at: "2014-01-26T22:52:33Z"
          created_at: "2006-09-07T19:48:15Z"
          id: 5273261262554249024
          name: Iusto laudantium assumenda.
          original_id: Voluptatem eum et rerum.
          pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1986-05-13T23:32:21Z"
          status: unknown
          transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
          completed_at: "2014-01-26T22:52:33Z"
          created_at: "2006-09-07T19:48:15Z"
          id: 5273261262554249024
          name: Iusto laudantium assumenda.
          original_id: Voluptatem eum et rerum.
          pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1986-05-13T23:32:21Z"
          status: unknown
          transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        - aip_id: E330131A-4516-F39A-1E98-7CBF64E7E788
          completed_at: "2014-01-26T22:52:33Z"
          created_at: "2006-09-07T19:48:15Z"
          id: 5273261262554249024
          name: Iusto laudantium assumenda.
          original_id: Voluptatem eum et rerum.
          pipeline_id: FF1D889F-0741-6290-783B-66E606310D86
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1986-05-13T23:32:21Z"
          status: unknown
          transfer_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        next_cursor: Dolorem praesentium asperiores.
      required:
      - items
    PipelineNotFound:
      type: object
      properties:
        id:
          type: string
          description: Identifier of missing pipeline
          example: Blanditiis sequi sunt neque velit debitis ducimus.
        message:
          type: string
          description: Message of error
          example: Provident hic aut quod.
      description: Pipeline not found
      example:
        id: Omnis quos.
        message: Totam veritatis vero aliquam unde.
      required:
      - message
      - id
    SubmitRequestBody:
      type: object
      properties:
        completed_dir:
          type: string
          example: Velit aperiam nemo dolorem.
        path:
          type: string
          example: Deserunt a enim cum ad quasi qui.
        pipeline:
          type: string
          example: Vitae fugit quis tempore animi ad ab.
        processing_config:
          type: string
          example: Beatae blanditiis qui et ut recusandae id.
        retention_period:
          type: string
          example: Saepe dolores aut quis delectus quia dolorem.
      example:
        completed_dir: Quibusdam suscipit tempore est.
        path: Rem et.
        pipeline: Minima sunt.
        processing_config: Cumque in qui voluptas et culpa beatae.
        retention_period: Ratione nisi in perferendis.
      required:
      - path
tags:
- name: batch
  description: The batch service manages batches of collections.
- name: collection
  description: The collection service manages packages being transferred to Archivematica.
- name: eark
  description: The eark service manages earkes of collections.
- name: pipeline
  description: The pipeline service manages Archivematica pipelines.
- name: swagger
  description: The swagger service serves the API swagger definition.
